const fs = require('fs')
const file = 'src/main.js'
const out = []
function L(...lines) { out.push(lines.join('\n')) }

L("import './style.css'")
L('')
L("const gameUrl = 'https://2048game.com/?ref=google-search-classic'")
L("const minesweeperUrl = 'https://minesweeperonline.com/'")
L("const sudokuUrl = 'https://www.nytimes.com/puzzles/sudoku?eafs_enabled=false'")
L("const solitaireUrl = 'https://lkforge.com/games/solitaire/'")
L("const pongUrl = 'https://vygam.com/pong'")
L('const goals = [128, 256, 512, 1024, 2048]')
L("const directions = ['up', 'right', 'down', 'left']")
L('')
L('let board = []')
L('let moveCount = 0')
L('let bestTile = 0')
L('let running = false')
L('let runTimer')
L('let boardRows = 4')
L('let boardColumns = 4')
L('let pongState = null')
L('')
L("const boardElement = document.querySelector('#board')")
L("const overlay = document.querySelector('#board-overlay')")
L("const moveElement = document.querySelector('#move-count')")
L("const bestElement = document.querySelector('#best-tile')")
L("const statusElement = document.querySelector('#run-status')")
L("const boardMeta = document.querySelector('#board-meta')")
L("const targetLabel = document.querySelector('#target-label')")
L("const engineLabel = document.querySelector('#engine-label')")
L("const launchLink = document.querySelector('#launch-link')")
L("const goalSelect = document.querySelector('#goal-select')")
L("const logElement = document.querySelector('#log')")
L("const logState = document.querySelector('#log-state')")
L("const runButton = document.querySelector('#run-button')")
L("const runLabel = document.querySelector('#run-label')")
L('')
L('function isPong(value) { return value && value.startsWith("pong-") }')
L('function pongDifficulty(value) { return (value || "").replace(/^pong-/, "") || "medium" }')
L('function pongRecordSeconds(difficulty) { return difficulty === "beginner" ? "1" : difficulty === "intermediate" ? "16" : "52" }')
L('function pongUrlForDifficulty(difficulty) { const q = new URLSearchParams(); q.set("difficulty", difficulty || "medium"); return `${pongUrl}?${q.toString()}` }')
L('function formatPongScore(value) { return typeof value === "number" && isFinite(value) ? String(value) : "0" }')

fs.writeFileSync('gen-ui-e.cjs', out.join('\n') + '\n', 'utf8')
console.log('gen-ui-e.cjs part1 written', out.length, 'lines')
