import { writeFileSync } from 'fs'

const t = []
const L = (...lines) => t.push(lines.join('\n'))

L("import './style.css'")
L('')
L("const gameUrl = 'https://2048game.com/?ref=google-search-classic'")
L("const minesweeperUrl = 'https://minesweeperonline.com/'")
L("const sudokuUrl = 'https://www.nytimes.com/puzzles/sudoku?eafs_enabled=false'")
L("const solitaireUrl = 'https://lkforge.com/games/solitaire/'")
L("const pongUrl = 'https://vygam.com/pong'")
L('const goals = [128, 256, 512, 1024, 2048]')
L("const directions = ['up', 'right', 'down', 'left']")
L('')
L('let board = []')
L('let moveCount = 0')
L('let bestTile = 0')
L('let running = false')
L('let runTimer')
L('let boardRows = 4')
L('let boardColumns = 4')
L('let pongState = null')
L('')
L("const boardElement = document.querySelector('#board')")
L("const overlay = document.querySelector('#board-overlay')")
L("const moveElement = document.querySelector('#move-count')")
L("const bestElement = document.querySelector('#best-tile')")
L("const statusElement = document.querySelector('#run-status')")
L("const boardMeta = document.querySelector('#board-meta')")
L("const targetLabel = document.querySelector('#target-label')")
L("const engineLabel = document.querySelector('#engine-label')")
L("const launchLink = document.querySelector('#launch-link')")
L("const goalSelect = document.querySelector('#goal-select')")
L("const logElement = document.querySelector('#log')")
L("const logState = document.querySelector('#log-state')")
L("const runButton = document.querySelector('#run-button')")
L("const runLabel = document.querySelector('#run-label')")
L('')
L('function isPong(value) { return value && value.startsWith("pong-") }')
L('function pongDifficulty(value) { return (value || "").replace(/^pong-/, "") || "medium" }')
L('function pongRecordSeconds(difficulty) { return difficulty === "beginner" ? "1" : difficulty === "intermediate" ? "16" : "52" }')
L('function pongUrlForDifficulty(difficulty) { const q = new URLSearchParams(); q.set("difficulty", difficulty || "medium"); return `${pongUrl}?${q.toString()}` }')
L('function formatPongScore(value) { return typeof value === "number" && isFinite(value) ? String(value) : "0" }')
L('')
L('function renderPong(state) {')
L("  if (!state) { if (boardMeta) boardMeta.textContent = 'FIRST TO 7 WINS'; return }")
L('  const pieces = []')
L("  if (state.statusText) pieces.push(state.statusText)")
L("  if (state.finished) pieces.push('finished')")
L("  if (state.won) pieces.push('won')")
L("  if (boardMeta) boardMeta.textContent = `PONG · ${formatPongScore(state.scoreMy)} - ${formatPongScore(state.scoreCpu)}`")
L('}')
L('')
L('function renderBoard() {')
L("  boardElement.innerHTML = ''")
L('  if (board.length === 0) return')
L('  const rows = boardRows || 4')
L('  const columns = boardColumns || 4')
L('  const tileSize = Math.floor(Math.min(boardElement.clientWidth / (columns + 1), boardElement.clientHeight / (rows + 1)))')
L('  const width = tileSize * columns, height = tileSize * rows')
L('  boardElement.style.width = `${width}px`')
L('  boardElement.style.height = `${height}px`')
L("  boardElement.style.setProperty('--tile', tileSize)")
L("  const colors = { 0: 'transparent', 2: '#eee4da', 4: '#ede0c8', 8: '#f2b179', 16: '#f59563', 32: '#f67c5f', 64: '#f65e3b', 128: '#edcf72', 256: '#edcc61', 512: '#edc850', 1024: '#edc53f', 2048: '#edc22e', 4096: '#edc22e' }")
L("  const textColors = { 0: '', 2: '#776e65', 4: '#776e65', 8: '#f9f6f2', 16: '#f9f6f2', 32: '#f9f6f2', 64: '#f9f6f2', 128: '#f9f6f2', 256: '#f9f6f2', 512: '#f9f6f2', 1024: '#f9f6f2', 2048: '#f9f6f2' }")
L('  for (let i = 0; i < board.length; i++) {')
L('    const value = board[i]')
L('    if (!value) continue')
L('    const row = Math.floor(i / 4), col = i % 4')
L("    const tile = document.createElement('div')")
L("    tile.className = 'tile tile-super'")
L("    tile.style.left = `${(col + 0.5) * tileSize - tileSize / 2}px`")
L("    tile.style.top = `${(row + 0.5) * tileSize - tileSize / 2}px`")
L("    tile.style.width = `${tileSize}px`")
L("    tile.style.height = `${tileSize}px`")
L("    tile.style.background = colors[value] || '#3c3a32'")
L("    tile.style.color = textColors[value] || '#f9f6f2'")
L('    tile.textContent = value')
L('    boardElement.appendChild(tile)')
L('  }')
L('}')
L('')
L('function log(message, kind) {')
L("  const row = document.createElement('div')")
L("  row.className = `logrow ${kind === 'accent' ? 'accent' : kind === 'muted' ? 'muted' : ''}`")
L("  row.innerHTML = `<span class='log-time'>${new Date().toLocaleTimeString()}</span><span>${message}</span>`")
L('  logElement.insertBefore(row, logElement.firstChild)')
L('  logElement.scrollTop = logElement.scrollHeight')
L("  if (kind === 'accent') logState.textContent = 'ACCENT'")
L("  if (kind === 'muted') logState.textContent = 'IDLE'")
L('}')

writeFileSync('gen-main.mjs', t.join('\n'), 'utf8')
console.log('gen-main.mjs partA written', t.length, 'lines')
